### ISSUE TITLE
Module names cannot contain _, but the Elm compiler will accept names with _

### ISSUE THREAD

**Issue by rupertlssmith** [eco-pro/project-metadata-utils#1]
This issue has been created to track adding _ to module names, as described here:

https://github.com/elm/project-metadata-utils/issues/12

**Comment by pravdomil** [comment]
It is closed? Is this repo deprecated?

**Comment by rupertlssmith** [comment]
Repo not deprecated, its purpose is to track and feed bug fixes to `elm/`.

====

Fixed in `elm/project-metadata-utils`  by:

https://github.com/elm/project-metadata-utils/pull/13

Release as version 1.0.2: 

https://github.com/elm/project-metadata-utils/blob/1.0.2/src/Elm/Module.elm#L75
